name: models
description: Shared models
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  util:
    path: ../../packages/util
  api:
    path: ../../packages/api



  flutter:
    sdk: flutter
#  firebase_core: ^4.0.0
#  cloud_firestore: ^6.0.0
#  firebase_storage: ^13.0.0
#  firebase_auth: ^6.0.0
#  google_sign_in: ^7.1.1
  flutter_riverpod: ^2.6.1
  google_maps_flutter: ^2.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0

dev_dependencies:
  build_runner: ^2.4.11