name: models
description: Shared models
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  util:
    path: ../../packages/util
  api:
    path: ../../packages/api



  flutter:
    sdk: flutter
#  firebase_core: ^4.0.0
#  cloud_firestore: ^6.0.0
#  firebase_storage: ^13.0.0
#  firebase_auth: ^6.0.0
#  google_sign_in: ^7.1.1
  flutter_riverpod: ^3.0.0-dev.17
  google_maps_flutter: ^2.9.0

  freezed_annotation: ^3.0.0
  json_serializable: ^6.8.0

dev_dependencies:
  freezed: 3.2.0
  build_runner: ^2.4.11
dependency_overrides:
  analyzer: ^7.6.0
  analyzer_plugin: 0.13.4
