name: elshaddai

packages:
  - apps/*
  - packages/*


scripts:
  build_runner:
    run: |
      flutter pub get
      flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner for all packages.