name: el_shaddai
description: "A multi-package Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.4.3 <4.0.0"

dev_dependencies:
  melos: ^6.0.0


# This is a sample, your assets and flutter section
# should not be here, they belong in the app package.
# flutter:
#   uses-material-design: true