name: util
description: Shared util
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  constants:
    path: ../../packages/constants
  api:
    path: ../../packages/api
  models:
    path: ../../packages/models
  flutter:
    sdk: flutter
  #  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  #  firebase_storage: ^13.0.0
  #  firebase_auth: ^6.0.0
  #  google_sign_in: ^7.1.1
  google_places_flutter: ^2.0.8
  dio: ^5.6.0
  flutter_riverpod: ^3.0.0-dev.17
  http: ^1.5.0
  fpdart: ^1.1.0
  retry: ^3.1.2
  google_maps_flutter: ^2.9.0
  time_range_picker: ^2.3.0
  auto_size_text: ^3.0.0
  freezed_annotation: ^3.0.0
dev_dependencies:
  freezed: 3.2.0
dependency_overrides:
  analyzer: ^7.6.0
  analyzer_plugin: 0.13.4
