name: constants
description: A package for shared constants.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
dependency_overrides:
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.4
