name: repositories
description: Shared repositories
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  util:
    path: ../../packages/util
  firebase:
    path: ../../packages/firebase
  constants:
    path: ../../packages/constants
  api:
    path: ../../packages/api
  models:
    path: ../../packages/models



  flutter:
    sdk: flutter
  #  firebase_core: ^4.0.0
  #  cloud_firestore: ^6.0.0
  #  firebase_storage: ^13.0.0
  #  firebase_auth: ^6.0.0
  #  google_sign_in: ^7.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  sign_in_with_apple: ^7.0.1


dev_dependencies:
  build_runner: ^2.4.11