name: firebase
description: Shared firebase
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  flutter_riverpod: ^3.0.0-dev.17
dependency_overrides:
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.4
