# Deploy to Firebase Hosting on PRs (Preview Channels)
name: Deploy to Firebase Hosting on PR
on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache Flutter dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # Build Flutter web app
      - run: cd apps/web && flutter build web --release --target=lib/main.dart --web-renderer html

      # Deploy preview channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EL_SHADD }}
          projectId: el-shadd
